max-lease-time 7200;
default-lease-time 7200;

subnet 10.0.4.0 netmask 255.255.255.0 {
    range 10.0.4.50 10.0.4.200;
    option routers 10.0.4.1;
    option domain-name "local.lan";
    option domain-name-servers 10.0.4.2, 10.0.4.3;
    option broadcast-address 10.0.4.255;
}

host printer-hp {
    hardware ethernet 00:11:22:33:44:ff;
    fixed-address 10.0.4.10;
}

host my-pc {
    hardware ethernet ad:11:22:fd:44:f3;
    fixed-address 10.0.4.11;
}